version: '3'



services:

  airflow:

    image: airflow:latest

    

    volumes:

      - ./airflow:/opt/airflow



    ports:

      - "9090:8080"



    command: airflow standalone